//catogory = sports tech culture 
//priority = true false

export const EventsData = [
    {
        id:1,
        link:"#techevent1",
        idname:"techevent1",
        category:"tech",
        priority: true,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50",
        value:50
    },
    {
        id:2,
        link:"#techevent2",
        idname:"techevent2",
        category:"tech",
        priority: false,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50",
        value:50
    },
    {
        id:3,
        link:"#techevent3",
        idname:"techevent3",
        category:"tech",
        priority: false,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50",
        value:50
    },
    {
        id:4,
        link:"#techevent4",
        idname:"techevent4",
        category:"tech",
        priority: false,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50",
        value:50
    },
    {
        id:5,
        link:"#techevent5",
        idname:"techevent5",
        category:"tech",
        priority: false,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50",
        value:50
    },
    {
        id:6,
        link:"#techevent6",
        idname:"techevent6",
        category:"tech",
        priority: false,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:7,
        link:"#techevent7",
        idname:"techevent7",
        category:"tech",
        priority: false,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:8,
        link:"#techevent8",
        idname:"techevent8",
        category:"tech",
        priority: true,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:9,
        link:"#techevent9",
        idname:"techevent9",
        category:"tech",
        priority: false,
        name: "TechEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:10,
        link:"#culturevent10",
        idname:"culturevent10",
        category:"culture",
        priority: true,
        name: "Hello World",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:11,
        link:"#culturevent11",
        idname:"culturevent11",
        category:"culture",
        priority: true,
        name: "cultureEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:12,
        category:"culture",
        priority: false,
        name: "cultureEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:13,
        category:"sports",
        priority: false,
        name: "sportsEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:14,
        category:"sports",
        priority: false,
        name: "sportsEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:15,
        category:"sports",
        priority: true,
        name: "sportsEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    },
    {
        id:16,
        category:"sports",
        priority: false,
        name: "sportsEvent",
        disc:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci tenetur dignissimos minus error laboriosam.",
        time:"3pm",
        date:"10-10-22",
        venue:"",
        reg:"Rs 50"
    }
]

 
   
